apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: live
spec:
  ingressClassName: traefik
  rules:
  - host: "lwcrm.store"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dolibarr
            port:
              number: 80
